GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY4MzMyNzM2MjU3ZjRkMzI0NDA3YWViYSIsImlhdCI6MTc0ODE4Mjg1MX0.5fkXMGororhGOYZmBcIYH_UZMGXDrEEiISalpZPUX4I
